name: Deploy DMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /opt/dms/Dormitory-Management-System

            git pull origin main

            docker compose down

            docker compose up -d --build
with:
  host: ${{ secrets.HOST }}
  username: ${{ secrets.USERNAME }}
  key: ${{ secrets.SSH_KEY }}
  debug: true